version: '3'

services:

  db:
    image:                  postgres:9.6-alpine
    hostname:               db
    container_name:         db
    restart:                always
    environment:
      POSTGRES_USER:        test
      POSTGRES_PASSWORD:    test
      POSTGRES_DB:          bkr
    volumes:
    -                       ./data/db_postgres:/var/lib/postgresql/data
    networks:
      -                     net-bkr-app
    ports:
      -                     "5432:5432"

  api:
    image:                  local/bkr-python:latest
    hostname:               api
    container_name:         api
    restart:                always
    environment:
      FLASK_ENV:            development
      DATABASE_URL:         postgres://test:test@db:5432/bkr
      JWT_SECRET_KEY:       v3rys3cr3tk3y
    volumes:
      -                     .:/app
    networks:
      -                     net-bkr-app
    depends_on:
      -                     db
    command:                python /app/run.py
    ports:
      -                     "5000:5000"

networks:
  net-bkr-app:
    driver:                 bridge