version: '3'

services:

  db:
    image:                  postgres:9.6-alpine
    hostname:               db
    container_name:         db
    restart:                always
    environment:
      POSTGRES_USER:        bkr-user
      POSTGRES_PASSWORD:    bkr-pass
      POSTGRES_DB:          bkr-db
    volumes:
    -                       ./data/db_postgres:/var/lib/postgresql/data
    networks:
      -                     net-bkr-api
    ports:
      -                     "5432:5432"

  api:
    build:                  .
    hostname:               api
    container_name:         api
    restart:                always
    environment:
      FLASK_ENV:            development
      DATABASE_URL:         postgresql://bkr-user:bkr-pass@db:5432/bkr-db
      JWT_SECRET_KEY:       v3rys3cr3tk3y
      PORT:                 5000
    networks:
      -                     net-bkr-api
    depends_on:
      -                     db
    ports:
      -                     "5000:5000"

networks:
  net-bkr-api:
    driver:                 bridge